"""add created_at to favorites

Revision ID: 00de2ce4e72a
Revises: 
Create Date: 2026-06-08 01:26:36.196344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00de2ce4e72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post_favorites', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
